#pragma once

#include <unordered_map>
#include <string>

std::unordered_map<std::string, uint8_t> seq2binTable = { {"AAAA", 0}, {"AAAC", 2}, {"AAAG", 1}, {"AAAT", 3},
                                                         {"AACA", 8}, {"AACC", 10}, {"AACG", 9}, {"AACT", 11},
                                                         {"AAGA", 4}, {"AAGC", 6}, {"AAGG", 5}, {"AAGT", 7},
                                                         {"AATA", 12}, {"AATC", 14}, {"AATG", 13}, {"AATT", 15},
                                                         {"ACAA", 32}, {"ACAC", 34}, {"ACAG", 33}, {"ACAT", 35},
                                                         {"ACCA", 40}, {"ACCC", 42}, {"ACCG", 41}, {"ACCT", 43},
                                                         {"ACGA", 36}, {"ACGC", 38}, {"ACGG", 37}, {"ACGT", 39},
                                                         {"ACTA", 44}, {"ACTC", 46}, {"ACTG", 45}, {"ACTT", 47},
                                                         {"AGAA", 16}, {"AGAC", 18}, {"AGAG", 17}, {"AGAT", 19},
                                                         {"AGCA", 24}, {"AGCC", 26}, {"AGCG", 25}, {"AGCT", 27},
                                                         {"AGGA", 20}, {"AGGC", 22}, {"AGGG", 21}, {"AGGT", 23},
                                                         {"AGTA", 28}, {"AGTC", 30}, {"AGTG", 29}, {"AGTT", 31},
                                                         {"ATAA", 48}, {"ATAC", 50}, {"ATAG", 49}, {"ATAT", 51},
                                                         {"ATCA", 56}, {"ATCC", 58}, {"ATCG", 57}, {"ATCT", 59},
                                                         {"ATGA", 52}, {"ATGC", 54}, {"ATGG", 53}, {"ATGT", 55},
                                                         {"ATTA", 60}, {"ATTC", 62}, {"ATTG", 61}, {"ATTT", 63},
                                                         {"CAAA", 128}, {"CAAC", 130}, {"CAAG", 129}, {"CAAT", 131},
                                                         {"CACA", 136}, {"CACC", 138}, {"CACG", 137}, {"CACT", 139},
                                                         {"CAGA", 132}, {"CAGC", 134}, {"CAGG", 133}, {"CAGT", 135},
                                                         {"CATA", 140}, {"CATC", 142}, {"CATG", 141}, {"CATT", 143},
                                                         {"CCAA", 160}, {"CCAC", 162}, {"CCAG", 161}, {"CCAT", 163},
                                                         {"CCCA", 168}, {"CCCC", 170}, {"CCCG", 169}, {"CCCT", 171},
                                                         {"CCGA", 164}, {"CCGC", 166}, {"CCGG", 165}, {"CCGT", 167},
                                                         {"CCTA", 172}, {"CCTC", 174}, {"CCTG", 173}, {"CCTT", 175},
                                                         {"CGAA", 144}, {"CGAC", 146}, {"CGAG", 145}, {"CGAT", 147},
                                                         {"CGCA", 152}, {"CGCC", 154}, {"CGCG", 153}, {"CGCT", 155},
                                                         {"CGGA", 148}, {"CGGC", 150}, {"CGGG", 149}, {"CGGT", 151},
                                                         {"CGTA", 156}, {"CGTC", 158}, {"CGTG", 157}, {"CGTT", 159},
                                                         {"CTAA", 176}, {"CTAC", 178}, {"CTAG", 177}, {"CTAT", 179},
                                                         {"CTCA", 184}, {"CTCC", 186}, {"CTCG", 185}, {"CTCT", 187},
                                                         {"CTGA", 180}, {"CTGC", 182}, {"CTGG", 181}, {"CTGT", 183},
                                                         {"CTTA", 188}, {"CTTC", 190}, {"CTTG", 189}, {"CTTT", 191},
                                                         {"GAAA", 64}, {"GAAC", 66}, {"GAAG", 65}, {"GAAT", 67},
                                                         {"GACA", 72}, {"GACC", 74}, {"GACG", 73}, {"GACT", 75},
                                                         {"GAGA", 68}, {"GAGC", 70}, {"GAGG", 69}, {"GAGT", 71},
                                                         {"GATA", 76}, {"GATC", 78}, {"GATG", 77}, {"GATT", 79},
                                                         {"GCAA", 96}, {"GCAC", 98}, {"GCAG", 97}, {"GCAT", 99},
                                                         {"GCCA", 104}, {"GCCC", 106}, {"GCCG", 105}, {"GCCT", 107},
                                                         {"GCGA", 100}, {"GCGC", 102}, {"GCGG", 101}, {"GCGT", 103},
                                                         {"GCTA", 108}, {"GCTC", 110}, {"GCTG", 109}, {"GCTT", 111},
                                                         {"GGAA", 80}, {"GGAC", 82}, {"GGAG", 81}, {"GGAT", 83},
                                                         {"GGCA", 88}, {"GGCC", 90}, {"GGCG", 89}, {"GGCT", 91},
                                                         {"GGGA", 84}, {"GGGC", 86}, {"GGGG", 85}, {"GGGT", 87},
                                                         {"GGTA", 92}, {"GGTC", 94}, {"GGTG", 93}, {"GGTT", 95},
                                                         {"GTAA", 112}, {"GTAC", 114}, {"GTAG", 113}, {"GTAT", 115},
                                                         {"GTCA", 120}, {"GTCC", 122}, {"GTCG", 121}, {"GTCT", 123},
                                                         {"GTGA", 116}, {"GTGC", 118}, {"GTGG", 117}, {"GTGT", 119},
                                                         {"GTTA", 124}, {"GTTC", 126}, {"GTTG", 125}, {"GTTT", 127},
                                                         {"TAAA", 192}, {"TAAC", 194}, {"TAAG", 193}, {"TAAT", 195},
                                                         {"TACA", 200}, {"TACC", 202}, {"TACG", 201}, {"TACT", 203},
                                                         {"TAGA", 196}, {"TAGC", 198}, {"TAGG", 197}, {"TAGT", 199},
                                                         {"TATA", 204}, {"TATC", 206}, {"TATG", 205}, {"TATT", 207},
                                                         {"TCAA", 224}, {"TCAC", 226}, {"TCAG", 225}, {"TCAT", 227},
                                                         {"TCCA", 232}, {"TCCC", 234}, {"TCCG", 233}, {"TCCT", 235},
                                                         {"TCGA", 228}, {"TCGC", 230}, {"TCGG", 229}, {"TCGT", 231},
                                                         {"TCTA", 236}, {"TCTC", 238}, {"TCTG", 237}, {"TCTT", 239},
                                                         {"TGAA", 208}, {"TGAC", 210}, {"TGAG", 209}, {"TGAT", 211},
                                                         {"TGCA", 216}, {"TGCC", 218}, {"TGCG", 217}, {"TGCT", 219},
                                                         {"TGGA", 212}, {"TGGC", 214}, {"TGGG", 213}, {"TGGT", 215},
                                                         {"TGTA", 220}, {"TGTC", 222}, {"TGTG", 221}, {"TGTT", 223},
                                                         {"TTAA", 240}, {"TTAC", 242}, {"TTAG", 241}, {"TTAT", 243},
                                                         {"TTCA", 248}, {"TTCC", 250}, {"TTCG", 249}, {"TTCT", 251},
                                                         {"TTGA", 244}, {"TTGC", 246}, {"TTGG", 245}, {"TTGT", 247},
                                                         {"TTTA", 252}, {"TTTC", 254}, {"TTTG", 253}, {"TTTT", 255},
                                                          };


std::unordered_map<uint8_t, std::string> bin2seqTable = { {0, "AAAA"},{2, "AAAC"},{1, "AAAG"},{3, "AAAT"},
                                                          {8, "AACA"},{10, "AACC"},{9, "AACG"},{11, "AACT"},
                                                          {4, "AAGA"},{6, "AAGC"},{5, "AAGG"},{7, "AAGT"},
                                                          {12, "AATA"},{14, "AATC"},{13, "AATG"},{15, "AATT"},
                                                          {32, "ACAA"},{34, "ACAC"},{33, "ACAG"},{35, "ACAT"},
                                                          {40, "ACCA"},{42, "ACCC"},{41, "ACCG"},{43, "ACCT"},
                                                          {36, "ACGA"},{38, "ACGC"},{37, "ACGG"},{39, "ACGT"},
                                                          {44, "ACTA"},{46, "ACTC"},{45, "ACTG"},{47, "ACTT"},
                                                          {16, "AGAA"},{18, "AGAC"},{17, "AGAG"},{19, "AGAT"},
                                                          {24, "AGCA"},{26, "AGCC"},{25, "AGCG"},{27, "AGCT"},
                                                          {20, "AGGA"},{22, "AGGC"},{21, "AGGG"},{23, "AGGT"},
                                                          {28, "AGTA"},{30, "AGTC"},{29, "AGTG"},{31, "AGTT"},
                                                          {48, "ATAA"},{50, "ATAC"},{49, "ATAG"},{51, "ATAT"},
                                                          {56, "ATCA"},{58, "ATCC"},{57, "ATCG"},{59, "ATCT"},
                                                          {52, "ATGA"},{54, "ATGC"},{53, "ATGG"},{55, "ATGT"},
                                                          {60, "ATTA"},{62, "ATTC"},{61, "ATTG"},{63, "ATTT"},
                                                          {128, "CAAA"},{130, "CAAC"},{129, "CAAG"},{131, "CAAT"},
                                                          {136, "CACA"},{138, "CACC"},{137, "CACG"},{139, "CACT"},
                                                          {132, "CAGA"},{134, "CAGC"},{133, "CAGG"},{135, "CAGT"},
                                                          {140, "CATA"},{142, "CATC"},{141, "CATG"},{143, "CATT"},
                                                          {160, "CCAA"},{162, "CCAC"},{161, "CCAG"},{163, "CCAT"},
                                                          {168, "CCCA"},{170, "CCCC"},{169, "CCCG"},{171, "CCCT"},
                                                          {164, "CCGA"},{166, "CCGC"},{165, "CCGG"},{167, "CCGT"},
                                                          {172, "CCTA"},{174, "CCTC"},{173, "CCTG"},{175, "CCTT"},
                                                          {144, "CGAA"},{146, "CGAC"},{145, "CGAG"},{147, "CGAT"},
                                                          {152, "CGCA"},{154, "CGCC"},{153, "CGCG"},{155, "CGCT"},
                                                          {148, "CGGA"},{150, "CGGC"},{149, "CGGG"},{151, "CGGT"},
                                                          {156, "CGTA"},{158, "CGTC"},{157, "CGTG"},{159, "CGTT"},
                                                          {176, "CTAA"},{178, "CTAC"},{177, "CTAG"},{179, "CTAT"},
                                                          {184, "CTCA"},{186, "CTCC"},{185, "CTCG"},{187, "CTCT"},
                                                          {180, "CTGA"},{182, "CTGC"},{181, "CTGG"},{183, "CTGT"},
                                                          {188, "CTTA"},{190, "CTTC"},{189, "CTTG"},{191, "CTTT"},
                                                          {64, "GAAA"},{66, "GAAC"},{65, "GAAG"},{67, "GAAT"},
                                                          {72, "GACA"},{74, "GACC"},{73, "GACG"},{75, "GACT"},
                                                          {68, "GAGA"},{70, "GAGC"},{69, "GAGG"},{71, "GAGT"},
                                                          {76, "GATA"},{78, "GATC"},{77, "GATG"},{79, "GATT"},
                                                          {96, "GCAA"},{98, "GCAC"},{97, "GCAG"},{99, "GCAT"},
                                                          {104, "GCCA"},{106, "GCCC"},{105, "GCCG"},{107, "GCCT"},
                                                          {100, "GCGA"},{102, "GCGC"},{101, "GCGG"},{103, "GCGT"},
                                                          {108, "GCTA"},{110, "GCTC"},{109, "GCTG"},{111, "GCTT"},
                                                          {80, "GGAA"},{82, "GGAC"},{81, "GGAG"},{83, "GGAT"},
                                                          {88, "GGCA"},{90, "GGCC"},{89, "GGCG"},{91, "GGCT"},
                                                          {84, "GGGA"},{86, "GGGC"},{85, "GGGG"},{87, "GGGT"},
                                                          {92, "GGTA"},{94, "GGTC"},{93, "GGTG"},{95, "GGTT"},
                                                          {112, "GTAA"},{114, "GTAC"},{113, "GTAG"},{115, "GTAT"},
                                                          {120, "GTCA"},{122, "GTCC"},{121, "GTCG"},{123, "GTCT"},
                                                          {116, "GTGA"},{118, "GTGC"},{117, "GTGG"},{119, "GTGT"},
                                                          {124, "GTTA"},{126, "GTTC"},{125, "GTTG"},{127, "GTTT"},
                                                          {192, "TAAA"},{194, "TAAC"},{193, "TAAG"},{195, "TAAT"},
                                                          {200, "TACA"},{202, "TACC"},{201, "TACG"},{203, "TACT"},
                                                          {196, "TAGA"},{198, "TAGC"},{197, "TAGG"},{199, "TAGT"},
                                                          {204, "TATA"},{206, "TATC"},{205, "TATG"},{207, "TATT"},
                                                          {224, "TCAA"},{226, "TCAC"},{225, "TCAG"},{227, "TCAT"},
                                                          {232, "TCCA"},{234, "TCCC"},{233, "TCCG"},{235, "TCCT"},
                                                          {228, "TCGA"},{230, "TCGC"},{229, "TCGG"},{231, "TCGT"},
                                                          {236, "TCTA"},{238, "TCTC"},{237, "TCTG"},{239, "TCTT"},
                                                          {208, "TGAA"},{210, "TGAC"},{209, "TGAG"},{211, "TGAT"},
                                                          {216, "TGCA"},{218, "TGCC"},{217, "TGCG"},{219, "TGCT"},
                                                          {212, "TGGA"},{214, "TGGC"},{213, "TGGG"},{215, "TGGT"},
                                                          {220, "TGTA"},{222, "TGTC"},{221, "TGTG"},{223, "TGTT"},
                                                          {240, "TTAA"},{242, "TTAC"},{241, "TTAG"},{243, "TTAT"},
                                                          {248, "TTCA"},{250, "TTCC"},{249, "TTCG"},{251, "TTCT"},
                                                          {244, "TTGA"},{246, "TTGC"},{245, "TTGG"},{247, "TTGT"},
                                                          {252, "TTTA"},{254, "TTTC"},{253, "TTTG"},{255, "TTTT"},
                                                           };
